AUTHORS = ["Aurélien Duboc", "Nicolas Bonnet"]
GITHUB_ACCOUNTS = ["https://github.com/zteeed", "https://github.com/bonnetn"]
VERSION = 'v2'
REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_STREAM_USERS = 'update_users'
REDIS_STREAM_CHALLENGES = 'update_challenges'
CONSUMER_GROUP_NAME = 'rootme'
UPDATE_TIMEOUT = 60
REQUEST_TIMEOUT = 3
